### ISSUE TITLE
您好，请问您的pt文件，训练好的模型可以发一下嘛？十分感谢！

### ISSUE THREAD

**Issue by luczzey** [yaolu-zjut/Dynamic-Graphs-Construction#2]
您好，请问您的pt文件，训练好的模型可以发一下嘛？十分感谢！

**Comment by luczzey** [comment]
> 您好，请问您的pt文件，训练好的模型可以发一下嘛？十分感谢！

我的邮箱
779708337@qq.com

**Comment by yaolu-zjut** [comment]
请问您需要哪些，数量有点多，此外，所有模型您都可以自己训练，我们提供了训练的代码，您也可以使用其他任意预训练模型进行操作

**Comment by luczzey** [comment]
> 

十分感谢您的回复，我需要cResNet的文件，然后再试一下我这边的网络。万分感谢您的回复，祝好！

**Comment by yaolu-zjut** [comment]
您好，前几天有事耽搁了，这里是cResNet的预训练模型文件：
链接：https://pan.baidu.com/s/1m7ulSJdFC-3o4YNh14v5ZQ 
提取码：gp3j

**Comment by luczzey** [comment]
您好，再次感谢您在百忙之中回复！十分感谢您的分享，祝好！




一帮一生一起走*
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaolu-zjut/Dynamic-Graphs-Construction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yaolu-zjut/Dynamic-Graphs-Construction] 您好，请问您的pt文件，训练好的模型可以发一下嘛？十分感谢！ (Issue #2)





 
您好，前几天有事耽搁了，这里是cResNet的预训练模型文件：
 链接：https://pan.baidu.com/s/1m7ulSJdFC-3o4YNh14v5ZQ
 提取码：gp3j
